### ISSUE TITLE
freyaMachine: lastModified fails at runtime

### ISSUE THREAD

**Issue by ForNeVeR** [freya-fs/freya#133]
I've downloaded [`StaticFileServer` example](https://github.com/freya-fs/freya.examples/tree/master/StaticFileServer) and trying to enable `lastModified` configuration by uncommenting this line: https://github.com/freya-fs/freya.examples/blob/c5c16d6ee44112f0a292fe52571db88e0ed0a92f/StaticFileServer/src/StaticFileServer/Stage5.fs#L72

After that an application fails at runtime with the following reason:

```
Cannot cast the type of an object "lastModifiedConfiguration@61-3" to type "Microsoft.FSharp.Core.FSharpFunc`2[Freya.Core.Types+FreyaState,Microsoft.FSharp.Control.FSharpAsync`1[System.Tuple`2[Microsoft.FSharp.Core.FSharpOption`1[System.DateTime],Freya.Core.Types+FreyaState]]]".
```

Here's a call stack:
```
at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
at Freya.Machine.Configuration.tryGetOrElse@45.Invoke(FreyaMachineConfiguration x) at C:\projects\freya\src\Freya.Machine\Configuration.fs:line 45
at Freya.Machine.Extensions.Http.Decisions.ifModifiedSinceModified(FreyaMachineConfiguration config) at C:\projects\freya\src\Freya.Machine.Extensions.Http\Decisions.fs:line 72
at Freya.Machine.Extensions.Http.Decisions.operations@207-7.Invoke(FreyaMachineConfiguration config) at C:\projects\freya\src\Freya.Machine.Extensions.Http\Decisions.fs:line 207
at Freya.Machine.Extensions.Http.Decisions.systemDecision@33.Invoke(FreyaMachineConfiguration config) at C:\projects\freya\src\Freya.Machine.Extensions.Http\Decisions.fs:line 34
at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
at Hekate.Graph.mapNodes@303.Invoke(v v, Tuple`3 tupledArg) at C:\projects\hekate\src\Hekate\Hekate.fs:line 304
at Microsoft.FSharp.Collections.MapTreeModule.mapi[a,b,c](FSharpFunc`2 f, MapTree`2 m)
at Microsoft.FSharp.Collections.MapTreeModule.mapi[a,b,c](FSharpFunc`2 f, MapTree`2 m)
at Microsoft.FSharp.Collections.MapTreeModule.mapi[a,b,c](FSharpFunc`2 f, MapTree`2 m)
at Microsoft.FSharp.Collections.MapTreeModule.mapi[a,b,c](FSharpFunc`2 f, MapTree`2 m)
at Microsoft.FSharp.Collections.MapTreeModule.mapi[a,b,c](FSharpFunc`2 f, MapTree`2 m)
at Microsoft.FSharp.Collections.MapModule.Map[TKey,T,TResult](FSharpFunc`2 mapping, FSharpMap`2 table)
at Freya.Machine.Compilation.build(FreyaMachineConfiguration config, PrecompilationGraph graph) at C:\projects\freya\src\Freya.Machine\Compilation.fs:line 67
at Freya.Machine.Compilation.compile(FreyaMachineConfiguration config, PrecompilationGraph graph) at C:\projects\freya\src\Freya.Machine\Compilation.fs:line 76
at Freya.Machine.Reification.reify[a](FSharpFunc`2 machine) at C:\projects\freya\src\Freya.Machine\Reification.fs:line 64
at Freya.Machine.FreyaMachine.toPipeline@27.Invoke(FSharpFunc`2 machine) at C:\projects\freya\src\Freya.Machine\Machine.fs:line 27
at <StartupCode$StaticFileServer>.$StaticFileServer.Stage5..cctor() at T:\Temp\freya.examples\StaticFileServer\src\StaticFileServer\Stage5.fs:line 68
```

(The error message may be slightly unprecise because I've got it in Russian and done my best to translate it.)

This trouble reproduces in my personal project as well when I'm trying to use `lastModified`.

So, is it some known issue with `lastModified`? How can I help with solution of this problem?

**Comment by panesofglass** [comment]
@ForNeVeR, sorry about that. Yes, I think it's a known issue. @kolektiv, did you have any plans for this, or is it yet to be properly diagnosed?

**Comment by kolektiv** [comment]
I wasn't aware of it - now there's an issue I'll take a look :) thanks for raising it!
